# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/apps/windows/dot-net

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:    
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
  
- task: VSTest@2
  inputs:
    testAssemblyVer2: '**\graph-db-test-tests.dll'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PowerShell@2
  inputs:
    targetType: inline
    script: Install-Module -Name CosmosDB -Force; $cosmosDbContext = New-CosmosDbContext -Emulator -Database 'db001'; New-CosmosDbDatabase -Context $cosmosDbContext -Id 'db001'; New-CosmosDbCollection -Context $cosmosDbContext -Id 'col001' -PartitionKey 'partitionId' -OfferThroughput 50000 

- task: BatchScript@1
  inputs:
    filename: ./build-pipeline/run-graph-db-test.bat

- task: VSTest@2
  inputs:
    testAssemblyVer2: '**\graph-db-test-functional-test.dll'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

