# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/apps/windows/dot-net

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:    
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
  
- task: VSTest@2
  inputs:
    testAssemblyVer2: '**\graph-db-test-tests.dll'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: AzureCLI@1
  displayName: 'AZ Create CosmosDB '
  inputs:
    azureSubscription: '$(azure_connection)'
    scriptLocation: scriptPath
    scriptPath: ./build-pipeline/create-azure-resources.bat
    arguments: $(resource_group_name) $(cosmos_db_name)

- task: BatchScript@1
  inputs:
    filename: ./build-pipeline/run-graph-db-test.bat

task: VSTest@2
  inputs:
    testAssemblyVer2: '**\graph-db-test-functional-test.dll'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    overrideTestrunParameters: '-cosmosdbname $(cosmos_db_name) -key $(cosmos_db_key)'

- task: AzureCLI@1
  displayName: 'AZ Delete CosmosDB '
  inputs:
    azureSubscription: '$(azure_connection)'
    scriptLocation: inlineScript
    inlineScript: az cosmosdb delete --resource-group $(resource_group_name) --name $(cosmos_db_name)
